// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artMetaData.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addArtComment = `-- name: AddArtComment :one
INSERT INTO art_comments (art_id, user_id, comment)
VALUES ($1, $2, $3)
RETURNING id, art_id, user_id, comment, created_at
`

type AddArtCommentParams struct {
	ArtID   uuid.UUID
	UserID  uuid.UUID
	Comment string
}

func (q *Queries) AddArtComment(ctx context.Context, arg AddArtCommentParams) (ArtComment, error) {
	row := q.db.QueryRowContext(ctx, addArtComment, arg.ArtID, arg.UserID, arg.Comment)
	var i ArtComment
	err := row.Scan(
		&i.ID,
		&i.ArtID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const checkArtLikedByUser = `-- name: CheckArtLikedByUser :one
SELECT EXISTS (
    SELECT 1 FROM art_likes
    WHERE art_id = $1 AND user_id = $2
) AS liked
`

type CheckArtLikedByUserParams struct {
	ArtID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CheckArtLikedByUser(ctx context.Context, arg CheckArtLikedByUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkArtLikedByUser, arg.ArtID, arg.UserID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const deleteArtComment = `-- name: DeleteArtComment :one
DELETE FROM art_comments
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteArtCommentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteArtComment(ctx context.Context, arg DeleteArtCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteArtComment, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getArtCommentsByArtID = `-- name: GetArtCommentsByArtID :many
SELECT 
    ac.id,
    ac.art_id,
    ac.user_id,
    u.name AS user_name,
    u.image AS user_image,
    ac.comment,
    ac.created_at
FROM art_comments ac
JOIN users u ON u.id = ac.user_id
WHERE ac.art_id = $1
ORDER BY ac.created_at DESC
`

type GetArtCommentsByArtIDRow struct {
	ID        uuid.UUID
	ArtID     uuid.UUID
	UserID    uuid.UUID
	UserName  string
	UserImage sql.NullString
	Comment   string
	CreatedAt time.Time
}

func (q *Queries) GetArtCommentsByArtID(ctx context.Context, artID uuid.UUID) ([]GetArtCommentsByArtIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getArtCommentsByArtID, artID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtCommentsByArtIDRow
	for rows.Next() {
		var i GetArtCommentsByArtIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtID,
			&i.UserID,
			&i.UserName,
			&i.UserImage,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtCommentsCount = `-- name: GetArtCommentsCount :one
SELECT COUNT(*)::int AS comments_count
FROM art_comments
WHERE art_id = $1
`

func (q *Queries) GetArtCommentsCount(ctx context.Context, artID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getArtCommentsCount, artID)
	var comments_count int32
	err := row.Scan(&comments_count)
	return comments_count, err
}

const getArtLikesCount = `-- name: GetArtLikesCount :one
SELECT COUNT(*)::int AS likes_count
FROM art_likes
WHERE art_id = $1
`

func (q *Queries) GetArtLikesCount(ctx context.Context, artID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getArtLikesCount, artID)
	var likes_count int32
	err := row.Scan(&likes_count)
	return likes_count, err
}

const likeArt = `-- name: LikeArt :one
INSERT INTO art_likes (art_id, user_id)
VALUES ($1, $2)
RETURNING id, art_id, user_id, created_at
`

type LikeArtParams struct {
	ArtID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) LikeArt(ctx context.Context, arg LikeArtParams) (ArtLike, error) {
	row := q.db.QueryRowContext(ctx, likeArt, arg.ArtID, arg.UserID)
	var i ArtLike
	err := row.Scan(
		&i.ID,
		&i.ArtID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const unlikeArt = `-- name: UnlikeArt :one
DELETE FROM art_likes
WHERE art_id = $1 AND user_id = $2
RETURNING art_id
`

type UnlikeArtParams struct {
	ArtID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnlikeArt(ctx context.Context, arg UnlikeArtParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, unlikeArt, arg.ArtID, arg.UserID)
	var art_id uuid.UUID
	err := row.Scan(&art_id)
	return art_id, err
}
