// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id, name, description, venue, image, banner_image, event_date, status
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateEventParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Venue,
		arg.Image,
		arg.BannerImage,
		arg.EventDate,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEvent = `-- name: DeleteEvent :one
DELETE FROM events
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteEvent, id)
	err := row.Scan(&id)
	return id, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    name,
    description,
    venue,
    image,
    banner_image,
    event_date,
    status
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Venue,
		&i.Image,
		&i.BannerImage,
		&i.EventDate,
		&i.Status,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    name,
    description,
    venue,
    image,
    event_date,
    status
FROM events
ORDER BY created_at DESC
`

type ListEventsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.EventDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByMode = `-- name: ListEventsByMode :many
SELECT
    id,
    name,
    description,
    venue,
    image,
    event_date,
    status
FROM events
WHERE status = $1
ORDER BY event_date ASC
`

type ListEventsByModeRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) ListEventsByMode(ctx context.Context, status ModeOfConduct) ([]ListEventsByModeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByMode, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByModeRow
	for rows.Next() {
		var i ListEventsByModeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.EventDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT
    id,
    name,
    description,
    venue,
    image,
    event_date,
    status
FROM events
WHERE event_date >= CURRENT_DATE
ORDER BY event_date ASC
`

type ListUpcomingEventsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) ListUpcomingEvents(ctx context.Context) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingEventsRow
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.EventDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    venue = COALESCE($3, venue),
    image = COALESCE($4, image),
    banner_image = COALESCE($5, banner_image),
    event_date = COALESCE($6, event_date),
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $8
RETURNING id
`

type UpdateEventParams struct {
	Name        sql.NullString
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   sql.NullTime
	Status      NullModeOfConduct
	ID          uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Name,
		arg.Description,
		arg.Venue,
		arg.Image,
		arg.BannerImage,
		arg.EventDate,
		arg.Status,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
