// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_Attendees.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countEventAttendees = `-- name: CountEventAttendees :one
SELECT COUNT(*)::int
FROM event_attendees
WHERE event_id = $1
`

func (q *Queries) CountEventAttendees(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countEventAttendees, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const enrollUserToEvent = `-- name: EnrollUserToEvent :one
INSERT INTO event_attendees (
    id, event_id, user_id
)
VALUES (
    $1, $2, $3
)
RETURNING id
`

type EnrollUserToEventParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, enrollUserToEvent, arg.ID, arg.EventID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMyEventById = `-- name: GetMyEventById :one
SELECT e.id
FROM events e
JOIN event_attendees ea ON ea.event_id = e.id
WHERE ea.user_id = $1
AND ea.event_id = $2
LIMIT 1
`

type GetMyEventByIdParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetMyEventById(ctx context.Context, arg GetMyEventByIdParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getMyEventById, arg.UserID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listEventAttendees = `-- name: ListEventAttendees :many
SELECT 
    u.id,
    u.name,
    u.username,
    u.email,
    u.image
FROM users u
JOIN event_attendees ea ON ea.user_id = u.id
WHERE ea.event_id = $1
ORDER BY ea.joined_at ASC
`

type ListEventAttendeesRow struct {
	ID       uuid.UUID
	Name     string
	Username sql.NullString
	Email    string
	Image    sql.NullString
}

func (q *Queries) ListEventAttendees(ctx context.Context, eventID uuid.UUID) ([]ListEventAttendeesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventAttendeesRow
	for rows.Next() {
		var i ListEventAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEvents = `-- name: ListMyEvents :many
SELECT
    e.id,
    e.name,
    e.description,
    e.venue,
    e.image,
    e.event_date
FROM events e
JOIN event_attendees ea ON ea.event_id = e.id
WHERE ea.user_id = $1
ORDER BY e.event_date ASC
`

type ListMyEventsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	EventDate   time.Time
}

func (q *Queries) ListMyEvents(ctx context.Context, userID uuid.UUID) ([]ListMyEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyEventsRow
	for rows.Next() {
		var i ListMyEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.EventDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromEvent = `-- name: RemoveUserFromEvent :one
DELETE FROM event_attendees
WHERE event_id = $1 AND user_id = $2
RETURNING event_id
`

type RemoveUserFromEventParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveUserFromEvent(ctx context.Context, arg RemoveUserFromEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, removeUserFromEvent, arg.EventID, arg.UserID)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}
