// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountStatus string

const (
	AccountStatusPending  AccountStatus = "pending"
	AccountStatusApproved AccountStatus = "approved"
	AccountStatusBanned   AccountStatus = "banned"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus
	Valid         bool // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type ArtStatus string

const (
	ArtStatusPending  ArtStatus = "pending"
	ArtStatusApproved ArtStatus = "approved"
	ArtStatusRejected ArtStatus = "rejected"
)

func (e *ArtStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtStatus(s)
	case string:
		*e = ArtStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtStatus: %T", src)
	}
	return nil
}

type NullArtStatus struct {
	ArtStatus ArtStatus
	Valid     bool // Valid is true if ArtStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArtStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtStatus), nil
}

type ModeOfConduct string

const (
	ModeOfConductOnline  ModeOfConduct = "online"
	ModeOfConductOffline ModeOfConduct = "offline"
)

func (e *ModeOfConduct) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModeOfConduct(s)
	case string:
		*e = ModeOfConduct(s)
	default:
		return fmt.Errorf("unsupported scan type for ModeOfConduct: %T", src)
	}
	return nil
}

type NullModeOfConduct struct {
	ModeOfConduct ModeOfConduct
	Valid         bool // Valid is true if ModeOfConduct is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModeOfConduct) Scan(value interface{}) error {
	if value == nil {
		ns.ModeOfConduct, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModeOfConduct.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModeOfConduct) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModeOfConduct), nil
}

type UserRole string

const (
	UserRolePresident        UserRole = "president"
	UserRoleVicePresident    UserRole = "vice_president"
	UserRoleGeneralSecretary UserRole = "general_secretary"
	UserRoleLogistic         UserRole = "logistic"
	UserRoleSocialMediaHead  UserRole = "social_media_head"
	UserRoleContentHead      UserRole = "content_head"
	UserRoleCoreMember       UserRole = "core_member"
	UserRoleMember           UserRole = "member"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Art struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Image       string
	Tags        []string
	Status      ArtStatus
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ArtComment struct {
	ID        uuid.UUID
	ArtID     uuid.UUID
	UserID    uuid.UUID
	Comment   string
	CreatedAt time.Time
}

type ArtLike struct {
	ID        uuid.UUID
	ArtID     uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Event struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type EventAttendee struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	UserID   uuid.UUID
	JoinedAt time.Time
}

type User struct {
	ID                uuid.UUID
	Name              string
	Username          sql.NullString
	Password          string
	Email             string
	Description       sql.NullString
	BannerImage       sql.NullString
	Image             sql.NullString
	Batch             sql.NullString
	SocialLinks       json.RawMessage
	Status            AccountStatus
	Role              UserRole
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ResetToken        sql.NullString
	ResetTokenExpires sql.NullTime
}
