// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const checkUsrById = `-- name: CheckUsrById :one
SELECT 
    id,
    status,
    role
FROM users
WHERE id = $1
`

type CheckUsrByIdRow struct {
	ID     uuid.UUID
	Status AccountStatus
	Role   UserRole
}

func (q *Queries) CheckUsrById(ctx context.Context, id uuid.UUID) (CheckUsrByIdRow, error) {
	row := q.db.QueryRowContext(ctx, checkUsrById, id)
	var i CheckUsrByIdRow
	err := row.Scan(&i.ID, &i.Status, &i.Role)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password,
    batch
)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, '')
)
RETURNING id
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
	Batch    interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Batch,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllUser = `-- name: GetAllUser :many
SELECT 
    id,
    name,
    email,
    status,
    role,
    image
FROM users
`

type GetAllUserRow struct {
	ID     uuid.UUID
	Name   string
	Email  string
	Status AccountStatus
	Role   UserRole
	Image  sql.NullString
}

func (q *Queries) GetAllUser(ctx context.Context) ([]GetAllUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserRow
	for rows.Next() {
		var i GetAllUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.Role,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserApproved = `-- name: GetAllUserApproved :many
SELECT 
    id,
    name,
    role,
    description,
    image,
    social_links
FROM users WHERE status='approved'
`

type GetAllUserApprovedRow struct {
	ID          uuid.UUID
	Name        string
	Role        UserRole
	Description sql.NullString
	Image       sql.NullString
	SocialLinks json.RawMessage
}

func (q *Queries) GetAllUserApproved(ctx context.Context) ([]GetAllUserApprovedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserApproved)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserApprovedRow
	for rows.Next() {
		var i GetAllUserApprovedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Image,
			&i.SocialLinks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoreMembers = `-- name: GetCoreMembers :many
SELECT 
    id,
    name,
    email,
    status,
    role,
    image
FROM users
WHERE role != 'member'
  AND status != 'banned'
`

type GetCoreMembersRow struct {
	ID     uuid.UUID
	Name   string
	Email  string
	Status AccountStatus
	Role   UserRole
	Image  sql.NullString
}

func (q *Queries) GetCoreMembers(ctx context.Context) ([]GetCoreMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoreMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoreMembersRow
	for rows.Next() {
		var i GetCoreMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.Role,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT 
    id,
    name,
    username,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID          uuid.UUID
	Name        string
	Username    sql.NullString
	Email       string
	Batch       sql.NullString
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    name,
    email,
    password,
    image
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	Image    sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Image,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    id,
    name,
    username,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID          uuid.UUID
	Name        string
	Username    sql.NullString
	Email       string
	Batch       sql.NullString
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
}

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
	)
	return i, err
}

const patchUserAdmin = `-- name: PatchUserAdmin :one
UPDATE users
SET
    status = COALESCE($1::account_status, status),
    role = COALESCE($2::user_role, role),
    updated_at = NOW()
WHERE id = $3
RETURNING
    id,
    status,
    role
`

type PatchUserAdminParams struct {
	Status NullAccountStatus
	Role   NullUserRole
	ID     uuid.UUID
}

type PatchUserAdminRow struct {
	ID     uuid.UUID
	Status AccountStatus
	Role   UserRole
}

func (q *Queries) PatchUserAdmin(ctx context.Context, arg PatchUserAdminParams) (PatchUserAdminRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserAdmin, arg.Status, arg.Role, arg.ID)
	var i PatchUserAdminRow
	err := row.Scan(&i.ID, &i.Status, &i.Role)
	return i, err
}

const patchUserPassword = `-- name: PatchUserPassword :one
UPDATE users
SET
    password = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id
`

type PatchUserPasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) PatchUserPassword(ctx context.Context, arg PatchUserPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, patchUserPassword, arg.Password, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const patchUserProfile = `-- name: PatchUserProfile :one
UPDATE users
SET
    name = COALESCE($1::text, name),
    username = COALESCE($2::text, username),
    email = COALESCE($3::text, email),
    batch = COALESCE($4::text, batch),
    description = COALESCE($5::text, description),
    image = COALESCE($6::text, image),
    banner_image = COALESCE($7::text, banner_image),
    social_links = COALESCE($8::jsonb, social_links),
    updated_at = NOW()
WHERE id = $9
RETURNING
    id,
    name,
    username,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links
`

type PatchUserProfileParams struct {
	Name        sql.NullString
	Username    sql.NullString
	Email       sql.NullString
	Batch       sql.NullString
	Description sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	SocialLinks pqtype.NullRawMessage
	ID          uuid.UUID
}

type PatchUserProfileRow struct {
	ID          uuid.UUID
	Name        string
	Username    sql.NullString
	Email       string
	Batch       sql.NullString
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
}

func (q *Queries) PatchUserProfile(ctx context.Context, arg PatchUserProfileParams) (PatchUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserProfile,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Batch,
		arg.Description,
		arg.Image,
		arg.BannerImage,
		arg.SocialLinks,
		arg.ID,
	)
	var i PatchUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
	)
	return i, err
}
